Feat 3.x
fortinet/fortigate-autoscale-aws pull request #1
Opened 2020-09-10 16:39 UTC by JaydenLiang

2020-09-11 23:46 UTC, klc178 requested changes

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-tgw-new.vpc.template
> +            "Description": "Instance type for the FortiGates in the Auto Scaling group. There are t2.small and compute-optimized instances such as c4 and c5 available with different vCPU sizes and ba
```suggestion
            "Description": "Instance type for the FortiGates in the Auto Scaling group. Instance types are available with different vCPU sizes and bandwidths. For more information, see https://aws.amazon.com/ec2/instance-types/."
```

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "Instance type for the FortiGates in the Auto Scaling group. There are t2.small and compute-optimized instances such as c4 and c5 available with different vCPU sizes and ba
```suggestion
            "Description": "Instance type for the FortiGates in the Auto Scaling group. Instance types are available with different vCPU sizes and bandwidths. For more information, see https://aws.amazon.com/ec2/instance-types/."
```

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "FortiOS version."
Does not appear to have been applied.

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "Use this protocol to load balance traffic."
Does not appear to have been applied.

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "Add an optional pre-defined load balancer to route traffic to web service in the private subnets. You can optionally use your own one or decide to not need one."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "Optional. The destination path for health checks. This path must begin with a '/' character, and can be at most 1024 characters in length."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-main.template
> +            "Description": "Optional. Specify the DNS Name of an existing internal load balancer used to route traffic from a FortiGate to targets in a specified target group. Leave it blank if you d
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-new-vpc.template
> +            "Description": "FortiOS version."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-new-vpc.template
> +            "Description": "Use this protocol to load balance traffic."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-new-vpc.template
> +            "Description": "Add an optional pre-defined load balancer to route traffic to web service in the private subnets. You can optionally use your own one or decide to not need one."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-new-vpc.template
> +            "Description": "Optional. The destination path for health checks. This path must begin with a '/' character, and can be at most 1024 characters in length."
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-new-vpc.template
> +            "Description": "Optional. Specify the DNS Name of an existing internal load balancer used to route traffic from a FortiGate to targets in a specified target group. Leave it blank if you d
applied?

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-tgw-new-vpc.template
> +            "Description": "Instance type for the FortiGates in the Auto Scaling group. There are t2.small and compute-optimized instances such as c4 and c5 available with different vCPU sizes and ba
```suggestion
            "Description": "Instance type for the FortiGates in the Auto Scaling group. Instance types are available with different vCPU sizes and bandwidths. For more information, see https://aws.amazon.com/ec2/instance-types/."
```

2020-09-11 23:46 UTC, klc178 commented on templates/autoscale-tgw-new-vpc.template
> +            "Description": "FortiOS version."
```suggestion
	            "Description": "FortiOS version supported by FortiGate Autoscale for AWS."
```

2020-09-11 23:46 UTC, klc178 commented on templates/create-db-table.template
> +            "Description": "The comma-delimited list of arn of DynamoDB tables created in this stack.",
```suggestion
            "Description": "The comma-delimited list of ARNs for DynamoDB tables created in this stack.",
```

2020-09-11 23:46 UTC, klc178 commented on templates/create-hybrid-auto-scaling-group.template
> +            "Description": "Instance type to launch as FortiGate On-Demand instances. There are t2.small and compute-optimized instances such as c4 and c5 available with different vCPU sizes and band
```suggestion
            "Description": "Instance type for the FortiGates in the Auto Scaling group. Instance types are available with different vCPU sizes and bandwidths. For more information, see https://aws.amazon.com/ec2/instance-types/."
```

2020-09-12 00:23 UTC, JaydenLiang commented on templates/autoscale-tgw-new-vpc.template
> +	            "Description": "FortiOS version supported by FortiGate Autoscale for AWS."
```suggestion
            "Description": "FortiOS version supported by FortiGate Autoscale for AWS."
```

2020-09-12 00:48 UTC, klc178 approved these changes
The changes in https://github.com/fortinet/fortigate-autoscale-aws/pull/1/commits/75c3d3ab774b58dd24967be72e68eba93cf72053 look good.

2020-09-12 00:48 UTC, klc178 approved these changes
Changes in https://github.com/fortinet/fortigate-autoscale-aws/pull/1/commits/2959085ee59cea60f31d40587c9570c4380edf72 look good.

2020-09-12 00:51 UTC, jamie-pate approved these changes

2020-09-12 00:54 UTC, merged