Doc update 3.2.1
fortinet/fortigate-autoscale-aws pull request #34
Opened 2021-01-28 19:16 UTC by JaydenLiang

documentation related update for:
1. feature FAZ integration
2. FOS support 6.4.4

2021-02-01 19:04 UTC, jamie-pate approved these changes

2021-02-04 03:41 UTC, klc178 requested changes

2021-02-04 03:41 UTC, klc178 commented on templates/autoscale-existing-vpc.template.yaml
> +                default: FortiGate PSK secret key
```suggestion
                default: FortiGate PSK secret
```

2021-02-04 03:41 UTC, klc178 commented on templates/autoscale-existing-vpc.template.yaml
> +                default: FortiGate PSK secret key
After a discussion, the conclusion was to leave it as is.

2021-02-04 03:41 UTC, klc178 commented on templates/autoscale-main.template.yaml
> +                default: FortiGate PSK secret key
```suggestion
                default: FortiGate PSK secret
```

2021-02-04 03:41 UTC, klc178 commented on templates/autoscale-new-vpc.template.yaml
> +                default: FortiGate PSK secret key
```suggestion
                default: FortiGate PSK secret
```

2021-02-04 03:41 UTC, klc178 commented on templates/autoscale-tgw-new-vpc.template.yaml
> +                default: FortiGate PSK secret key
```suggestion
                default: FortiGate PSK secret
```

2021-02-04 17:32 UTC, klc178 approved these changes

2021-02-04 19:20 UTC, klc178 approved these changes

2021-02-04 23:48 UTC, merged